name: Build
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git unzip mingw-w64-ucrt-x86_64-gcc
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
      - name: Prepare version file
        run: echo $GITHUB_SHA > version
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v3.26.0-stable
          artifacts: "algod.exe,goal.exe,kmd.exe,algokey.exe"
